format = """
$sudo\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$custom\
$character"""

# move the rest of the prompt to the right
right_format = """
$golang\
$php\
$python\
$env_var"""

add_newline = false

#command_timeout = 60000

########
# Left #
########
[sudo]
disabled = false
format = '[$symbol]($style) '
symbol = 'ğŸ§™ğŸ½'

[directory]
disabled = false
truncation_length = 1
truncation_symbol = 'ï» '

[git_branch]
disabled = false
format = "[î‚¶]($style)[[îœ¥ ](bg:purple fg:bright-purple)$branch](bg:purple fg:bright-purple)[î‚´ ]($style)"
style = "bg:none fg:purple"

[git_commit]
disabled = false

[git_state]
disabled = true

[git_status]
disabled = false
format = "[î‚¶]($style)[$all_status$ahead_behind](bg:#24263a fg:#b4befe)[î‚´ ]($style)"
style = "bg:none fg:#24263a"
conflicted = "="
ahead =	"â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
up_to_date = "ï˜«"
untracked = "?"
stashed = "ó°†“"
modified = "!"
staged = "+$"
renamed = "Â»"
deleted = "ï™•"

[character]
success_symbol = '[î©±](bold green)'
error_symbol = '[î©±](bold red)'

#########
# Right #
#########

[php]
disabled = false
format = "[î‚¶]($style)[$symbol](bg:purple)[î‚´ ]($style)"
style = "bg:none fg:purple"
symbol = 'ğŸ˜'

[python]
disabled = false
format = "[î‚¶]($style)[$symbol](bg:green)[î‚´ ]($style)"
style = "bg:none fg:green"
symbol = 'ğŸ'

[golang]
disabled = false
format = "[î‚¶]($style)[$symbol](bg:cyan)[î‚´ ]($style)"
style = "bg:none fg:cyan"
symbol = 'ğŸ‡¬'
