format = """
$sudo\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$golang\
$nodejs\
$php\
$python\
$env_var\
$custom\
$character"""

# move the rest of the prompt to the right
right_format = """
$git_metrics"""

add_newline = false

#command_timeout = 60000

########
# Left #
########
[sudo]
disabled = false
format = '[$symbol]($style) '
symbol = 'ğŸ§™ğŸ½'

[directory]
disabled = false
truncation_length = 2
truncation_symbol = './'

[php]
disabled = false
format = '[{$symbol}]($style) '
symbol = 'ğŸ˜'

[git_branch]
disabled = false
symbol = 'îœ¥ '

[git_commit]
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false

[character]
success_symbol = '[ï¡](bold green)'
error_symbol = '[ï¡](bold red)'

#########
# Right #
#########
[git_metrics]
disabled = false
format = ' ([$added]($added_style)) ([$deleted]($deleted_style))'
